# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/steven/Desktop/65816_Interface_System/ZYBO_Master.xdc

# Block Designs: bd/Interface_Master_BD/Interface_Master_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD || ORIG_REF_NAME==Interface_Master_BD}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_processing_system7_0_0/Interface_Master_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_processing_system7_0_0 || ORIG_REF_NAME==Interface_Master_BD_processing_system7_0_0}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_clk_wiz_0_0/Interface_Master_BD_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_clk_wiz_0_0 || ORIG_REF_NAME==Interface_Master_BD_clk_wiz_0_0}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_AXIinterfacefor65816_0_0/Interface_Master_BD_AXIinterfacefor65816_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_AXIinterfacefor65816_0_0 || ORIG_REF_NAME==Interface_Master_BD_AXIinterfacefor65816_0_0}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_processing_system7_0_axi_periph_0/Interface_Master_BD_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Interface_Master_BD_processing_system7_0_axi_periph_0}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_rst_processing_system7_0_71M_0/Interface_Master_BD_rst_processing_system7_0_71M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_rst_processing_system7_0_71M_0 || ORIG_REF_NAME==Interface_Master_BD_rst_processing_system7_0_71M_0}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_xbar_0/Interface_Master_BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_xbar_0 || ORIG_REF_NAME==Interface_Master_BD_xbar_0}]

# IP: bd/Interface_Master_BD/ip/Interface_Master_BD_auto_pc_0/Interface_Master_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_auto_pc_0 || ORIG_REF_NAME==Interface_Master_BD_auto_pc_0}]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_processing_system7_0_0/Interface_Master_BD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Interface_Master_BD_processing_system7_0_0 || ORIG_REF_NAME==Interface_Master_BD_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_clk_wiz_0_0/Interface_Master_BD_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Interface_Master_BD_clk_wiz_0_0 || ORIG_REF_NAME==Interface_Master_BD_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_clk_wiz_0_0/Interface_Master_BD_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Interface_Master_BD_clk_wiz_0_0 || ORIG_REF_NAME==Interface_Master_BD_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_clk_wiz_0_0/Interface_Master_BD_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Interface_Master_BD_clk_wiz_0_0 || ORIG_REF_NAME==Interface_Master_BD_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_clk_wiz_0_0/Interface_Master_BD_clk_wiz_0_0_ooc.xdc

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_rst_processing_system7_0_71M_0/Interface_Master_BD_rst_processing_system7_0_71M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_rst_processing_system7_0_71M_0 || ORIG_REF_NAME==Interface_Master_BD_rst_processing_system7_0_71M_0}]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_rst_processing_system7_0_71M_0/Interface_Master_BD_rst_processing_system7_0_71M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Interface_Master_BD_rst_processing_system7_0_71M_0 || ORIG_REF_NAME==Interface_Master_BD_rst_processing_system7_0_71M_0}]

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_rst_processing_system7_0_71M_0/Interface_Master_BD_rst_processing_system7_0_71M_0_ooc.xdc

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_xbar_0/Interface_Master_BD_xbar_0_ooc.xdc

# XDC: bd/Interface_Master_BD/ip/Interface_Master_BD_auto_pc_0/Interface_Master_BD_auto_pc_0_ooc.xdc

# XDC: bd/Interface_Master_BD/Interface_Master_BD_ooc.xdc
